//------------------------------------------------------------------------------
<<<<<<< HEAD
// <otomatik üretildi>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod tekrar üretildi. 
// </otomatik üretildi>
=======
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
>>>>>>> master
//------------------------------------------------------------------------------

namespace DynamicDb.Pages {
    
    
    public partial class Dashboard {
        
        /// <summary>
<<<<<<< HEAD
        /// NavBar1 denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik üretilmiş alan.
        /// Değiştirmek için, alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::DynamicDb.Controls.NavBar NavBar1;
        
        /// <summary>
        /// form1 denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik üretilmiş alan.
        /// Değiştirmek için, alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
=======
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> master
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
<<<<<<< HEAD
        /// btnCreateDbLink denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik üretilmiş alan.
        /// Değiştirmek için, alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
=======
        /// btnCreateDbLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> master
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink btnCreateDbLink;
        
        /// <summary>
<<<<<<< HEAD
        /// btnCreateTableLink denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik üretilmiş alan.
        /// Değiştirmek için, alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
=======
        /// btnCreateTableLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> master
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink btnCreateTableLink;
        
        /// <summary>
<<<<<<< HEAD
        /// btnEditTableLink denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik üretilmiş alan.
        /// Değiştirmek için, alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
=======
        /// btnEditTableLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> master
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink btnEditTableLink;
        
        /// <summary>
<<<<<<< HEAD
        /// btnMyTablesLink denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik üretilmiş alan.
        /// Değiştirmek için, alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
=======
        /// btnMyTablesLink control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
>>>>>>> master
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink btnMyTablesLink;
    }
}
